# Generated by Django 4.2.25 on 2025-12-17 13:37

import api.materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content (HTML)', null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.materials.models.unique_file_path),
        ),
        migrations.AlterField(
            model_name='material',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=api.materials.models.unique_video_path),
        ),
    ]
