# Generated by Django 4.2.25 on 2025-12-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_quizattempt_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Maksimal percobaan pengerjaan kuis'),
        ),
    ]
