# Generated by Django 4.2.25 on 2025-12-14 15:48

import api.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_nisn_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.users.models.User.profile_upload_path),
        ),
    ]
