# Generated by Django 4.2.25 on 2025-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
